version: "3.8"

services:
  nextjsapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb?schema=public
    depends_on:
      - db
    volumes:
      - ./:/app
    working_dir: /app

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data

volumes:
  postgres:
    name: postgres
